import { describe, it, expect, beforeEach } from 'vitest'
import {
  getDisabledRules,
  generateToml,
  generateTomlWithMetadata,
} from '../src/utils/exportToml'
import { ruleSettingsStore } from '../src/utils/ruleSettings'
import type { RuffRule } from '../src/types/rules'

describe('exportToml', () => {
  const mockRules: RuffRule[] = [
    {
      code: 'E501',
      name: 'line-too-long',
      summary: 'Line too long',
      category: 'pycodestyle (E)',
      categoryCode: 'E',
      status: 'stable',
      documentUrl: 'https://docs.astral.sh/ruff/rules/line-too-long',
    },
    {
      code: 'F401',
      name: 'unused-import',
      summary: 'Module imported but unused',
      category: 'Pyflakes (F)',
      categoryCode: 'F',
      status: 'stable',
      documentUrl: 'https://docs.astral.sh/ruff/rules/unused-import',
    },
    {
      code: 'D100',
      name: 'undocumented-public-module',
      summary: 'Missing docstring in public module',
      category: 'pydocstyle (D)',
      categoryCode: 'D',
      status: 'stable',
      documentUrl:
        'https://docs.astral.sh/ruff/rules/undocumented-public-module',
    },
  ]

  beforeEach(() => {
    // 各テストの前にキャッシュをクリア
    ruleSettingsStore.clearCache()
  })

  describe('getDisabledRules', () => {
    it('無効化されたルールのみを返す', () => {
      // E501を無効化
      ruleSettingsStore.set('E501', { enabled: false })
      // F401を無効化
      ruleSettingsStore.set('F401', { enabled: false })
      // D100は有効（設定しない = デフォルトで有効）

      const disabled = getDisabledRules(mockRules)

      expect(disabled).toHaveLength(2)
      expect(disabled.map((r) => r.code)).toContain('E501')
      expect(disabled.map((r) => r.code)).toContain('F401')
      expect(disabled.map((r) => r.code)).not.toContain('D100')
    })

    it('全てのルールが有効な場合は空配列を返す', () => {
      // 全て有効（デフォルト）
      const disabled = getDisabledRules(mockRules)

      expect(disabled).toHaveLength(0)
    })

    it('全てのルールが無効な場合は全てを返す', () => {
      mockRules.forEach((rule) => {
        ruleSettingsStore.set(rule.code, { enabled: false })
      })

      const disabled = getDisabledRules(mockRules)

      expect(disabled).toHaveLength(3)
    })
  })

  describe('generateToml', () => {
    it('無効化されたルールをTOML形式で出力する', () => {
      // E501とF401を無効化
      ruleSettingsStore.set('E501', { enabled: false })
      ruleSettingsStore.set('F401', { enabled: false })

      const toml = generateToml(mockRules)

      // TOML形式の確認
      expect(toml).toContain('[tool.ruff]')
      expect(toml).toContain('ignore = [')
      expect(toml).toContain('"E501"')
      expect(toml).toContain('"F401"')
      expect(toml).toContain('# line-too-long')
      expect(toml).toContain('# unused-import')
    })

    it('ルールコード順にソートされる', () => {
      // F401, D100, E501 の順で無効化（アルファベット順ではない）
      ruleSettingsStore.set('F401', { enabled: false })
      ruleSettingsStore.set('D100', { enabled: false })
      ruleSettingsStore.set('E501', { enabled: false })

      const toml = generateToml(mockRules)

      // D100, E501, F401 の順になっているか確認
      const d100Index = toml.indexOf('"D100"')
      const e501Index = toml.indexOf('"E501"')
      const f401Index = toml.indexOf('"F401"')

      expect(d100Index).toBeLessThan(e501Index)
      expect(e501Index).toBeLessThan(f401Index)
    })

    it('無効化されたルールがない場合は適切なメッセージを表示', () => {
      const toml = generateToml(mockRules)

      expect(toml).toContain('[tool.ruff]')
      expect(toml).toContain('All rules are enabled')
      expect(toml).not.toContain('ignore = [')
    })

    it('1つだけ無効化されている場合は単数形を使用', () => {
      ruleSettingsStore.set('E501', { enabled: false })

      const toml = generateToml(mockRules)

      expect(toml).toContain('1 rule disabled')
    })

    it('複数無効化されている場合は複数形を使用', () => {
      ruleSettingsStore.set('E501', { enabled: false })
      ruleSettingsStore.set('F401', { enabled: false })

      const toml = generateToml(mockRules)

      expect(toml).toContain('2 rules disabled')
    })
  })

  describe('generateTomlWithMetadata', () => {
    it('メタデータを含むTOMLを生成', () => {
      ruleSettingsStore.set('E501', { enabled: false })

      const toml = generateTomlWithMetadata(mockRules, '0.1.0')

      expect(toml).toContain('# Generated by RuffMate')
      expect(toml).toContain('# Ruff version: 0.1.0')
      expect(toml).toContain('# Total rules: 3')
      expect(toml).toContain('# Disabled rules: 1')
      expect(toml).toContain('# Generated at:')
      expect(toml).toContain('[tool.ruff]')
      expect(toml).toContain('"E501"')
    })

    it('生成日時がISO 8601形式である', () => {
      const toml = generateTomlWithMetadata(mockRules, '0.1.0')

      // ISO 8601形式の日時を抽出
      const match = toml.match(/# Generated at: (.+)/)
      expect(match).not.toBeNull()

      if (match) {
        const timestamp = match[1]
        // ISO 8601形式かチェック（例: 2024-01-01T00:00:00.000Z）
        expect(timestamp).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/)
      }
    })
  })
})
