import { describe, it, expect, beforeEach } from 'vitest'
import {
  getDisabledRules,
  generateToml,
  generateTomlWithMetadata,
} from '../src/utils/exportToml'
import { ruleSettingsStore } from '../src/utils/ruleSettings'
import type { RuffRule } from '../src/types/rules'

describe('exportToml', () => {
  const mockRules: RuffRule[] = [
    {
      code: 'E501',
      name: 'line-too-long',
      summary: 'Line too long',
      category: 'pycodestyle (E)',
      categoryCode: 'E',
      status: 'stable',
      documentUrl: 'https://docs.astral.sh/ruff/rules/line-too-long',
    },
    {
      code: 'F401',
      name: 'unused-import',
      summary: 'Module imported but unused',
      category: 'Pyflakes (F)',
      categoryCode: 'F',
      status: 'stable',
      documentUrl: 'https://docs.astral.sh/ruff/rules/unused-import',
    },
    {
      code: 'D100',
      name: 'undocumented-public-module',
      summary: 'Missing docstring in public module',
      category: 'pydocstyle (D)',
      categoryCode: 'D',
      status: 'stable',
      documentUrl:
        'https://docs.astral.sh/ruff/rules/undocumented-public-module',
    },
  ]

  beforeEach(() => {
    // 各テストの前にキャッシュをクリア
    ruleSettingsStore.clearAll()
  })

  describe('getDisabledRules', () => {
    it('無効化されたルールのみを返す', () => {
      // E501を無効化
      ruleSettingsStore.set('E501', { enabled: false })
      // F401を無効化
      ruleSettingsStore.set('F401', { enabled: false })
      // D100は有効（設定しない = デフォルトで有効）

      const disabled = getDisabledRules(mockRules)

      expect(disabled).toHaveLength(2)
      expect(disabled.map((r) => r.code)).toContain('E501')
      expect(disabled.map((r) => r.code)).toContain('F401')
      expect(disabled.map((r) => r.code)).not.toContain('D100')
    })

    it('全てのルールが有効な場合は空配列を返す', () => {
      // 全て有効（デフォルト）
      const disabled = getDisabledRules(mockRules)

      expect(disabled).toHaveLength(0)
    })

    it('全てのルールが無効な場合は全てを返す', () => {
      mockRules.forEach((rule) => {
        ruleSettingsStore.set(rule.code, { enabled: false })
      })

      const disabled = getDisabledRules(mockRules)

      expect(disabled).toHaveLength(3)
    })
  })

  describe('generateToml', () => {
    it('無効化されたルールをTOML形式で出力する', () => {
      // E501とF401を無効化（コメント付き）
      ruleSettingsStore.set('E501', {
        enabled: false,
        comment: 'コーディング規約で許容',
      })
      ruleSettingsStore.set('F401', { enabled: false })

      const toml = generateToml(mockRules)

      // TOML形式の確認
      expect(toml).toContain('[tool.ruff.lint]')
      expect(toml).toContain('select = ["ALL"]')
      expect(toml).toContain('ignore = [')
      expect(toml).toContain('"E501",  # コーディング規約で許容')
      expect(toml).toContain('"F401",')
      // F401はコメントなし
      expect(toml).not.toContain('# unused-import')
    })

    it('ルールコード順にソートされる', () => {
      // F401, D100, E501 の順で無効化（アルファベット順ではない）
      ruleSettingsStore.set('F401', { enabled: false })
      ruleSettingsStore.set('D100', { enabled: false })
      ruleSettingsStore.set('E501', { enabled: false })

      const toml = generateToml(mockRules)

      // D100, E501, F401 の順になっているか確認
      const d100Index = toml.indexOf('"D100"')
      const e501Index = toml.indexOf('"E501"')
      const f401Index = toml.indexOf('"F401"')

      expect(d100Index).toBeLessThan(e501Index)
      expect(e501Index).toBeLessThan(f401Index)
    })

    it('無効化されたルールがない場合は適切なメッセージを表示', () => {
      const toml = generateToml(mockRules)

      expect(toml).toContain('[tool.ruff.lint]')
      expect(toml).toContain('select = ["ALL"]')
      expect(toml).toContain('All rules are enabled')
      expect(toml).not.toContain('ignore = [')
    })

    it('除外理由がある場合はコメントに表示される', () => {
      ruleSettingsStore.set('E501', {
        enabled: false,
        comment: 'プロジェクトのコーディング規約で許容',
      })

      const toml = generateToml(mockRules)

      expect(toml).toContain('"E501",  # プロジェクトのコーディング規約で許容')
    })

    it('除外理由がない場合はコメントを表示しない', () => {
      ruleSettingsStore.set('E501', { enabled: false })

      const toml = generateToml(mockRules)

      expect(toml).toContain('"E501",')
      // コメントなし
      expect(toml).not.toContain('# line-too-long')
    })
  })

  describe('generateTomlWithMetadata', () => {
    it('メタデータを含むTOMLを生成', () => {
      ruleSettingsStore.set('E501', { enabled: false })

      const toml = generateTomlWithMetadata(mockRules, '0.1.0')

      // メタデータが[tool.ruff.lint]の直後に配置されていることを確認
      expect(toml).toContain('[tool.ruff.lint]')
      expect(toml).toContain('# Generated by RuffMate at')
      expect(toml).toContain('# Ruff version: 0.1.0')
      expect(toml).toContain('# https://github.com/yourusername/RuffMate')
      expect(toml).toContain('select = ["ALL"]')
      expect(toml).toContain('"E501",')

      // コメントの順序を確認
      const lintIndex = toml.indexOf('[tool.ruff.lint]')
      const commentIndex = toml.indexOf('# Generated by RuffMate at')
      const selectIndex = toml.indexOf('select = ["ALL"]')

      expect(lintIndex).toBeLessThan(commentIndex)
      expect(commentIndex).toBeLessThan(selectIndex)
    })

    it('生成日時がISO 8601形式である', () => {
      const toml = generateTomlWithMetadata(mockRules, '0.1.0')

      // ISO 8601形式の日時を抽出
      const match = toml.match(/# Generated by RuffMate at (.+)/)
      expect(match).not.toBeNull()

      if (match) {
        const timestamp = match[1]
        // ISO 8601形式かチェック（例: 2024-01-01T00:00:00.000Z）
        expect(timestamp).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/)
      }
    })
  })
})
