import type { RuffRule } from '../types/rules'
import { ruleSettingsStore } from './ruleSettings'

/**
 * 無効化されたルールのリストを取得
 */
export function getDisabledRules(rules: RuffRule[]): RuffRule[] {
  return rules.filter((rule) => {
    const settings = ruleSettingsStore.getSync(rule.code)
    return !settings.enabled
  })
}

/**
 * pyproject.toml形式のRuff設定を生成
 */
export function generateToml(rules: RuffRule[]): string {
  const disabledRules = getDisabledRules(rules)

  if (disabledRules.length === 0) {
    return `[tool.ruff]
# All rules are enabled (no rules disabled in RuffMate)
`
  }

  // ルールコードでソート
  const sortedRules = [...disabledRules].sort((a, b) =>
    a.code.localeCompare(b.code)
  )

  // TOML生成
  let toml = `[tool.ruff]
# Disabled rules (generated by RuffMate)
# Total: ${sortedRules.length} rule${sortedRules.length !== 1 ? 's' : ''} disabled
ignore = [
`

  // 各ルールを追加
  sortedRules.forEach((rule, index) => {
    const isLast = index === sortedRules.length - 1
    toml += `    "${rule.code}",  # ${rule.name}${isLast ? '' : '\n'}`
  })

  toml += `
]
`

  return toml
}

/**
 * エクスポート用のメタデータを含むTOMLを生成
 */
export function generateTomlWithMetadata(
  rules: RuffRule[],
  ruffVersion: string
): string {
  const timestamp = new Date().toISOString()
  const disabledCount = getDisabledRules(rules).length

  const header = `# Generated by RuffMate
# https://github.com/yourusername/RuffMate
# Generated at: ${timestamp}
# Ruff version: ${ruffVersion}
# Total rules: ${rules.length}
# Disabled rules: ${disabledCount}

`

  return header + generateToml(rules)
}
